def tipos_processuais():

	tipos_processuais= [
		'abertura, registro e cumprimento de testamento',
		'adoção c/c destituição do poder familiar',
		'adoção',
		'agravo de execução penal',
		'agravo de instrumento',
		'agravo em recurso especial',
		'agravo em recurso especial',
		'agravo interno cível',
		'agravo interno',
		'agravo regimental criminal',
		'agravo regimental cível',
		'alienação judicial de bens',
		'alimentos',
		'alteração de regime de bens',
		'alvará judicial',
		'anulação e substituição de títulos ao portador',
		'apelação',
		'apreensão e depósito de coisa vendida com reserva de domínio',
		'apuração de infração administrativa às normas de proteção à criança ou adolescente',
		'apuração de irregularidades em entidades de atendimento',
		'arresto',
		'arrolamento comum',
		'arrolamento de bens',
		'arrolamento sumário',
		'auto de apreensão em flagrante',
		'auto de prisão em flagrante',
		'autorização judicial',
		'averiguação de paternidade',
		'ação civil coletiva',
		'ação civil de improbidade administrativa',
		'ação civil pública cível',
		'ação civil pública infância e juventude',
		'ação civil pública',
		'ação de alimentos',
		'ação de antecipação de tutela',
		'ação de aposentadoria por idade',
		'ação de concessão de auxílio doença',
		'ação de exigir contas',
		'ação de investigação de paternidade',
		'ação de partilha',
		'ação de salário maternidade',
		'ação indenizatória',
		'direta de inconstitucionalidade'
		'ação penal de competência do júri',
		'ação penal – procedimento ordinário',
		'ação penal',
		'ação popular',
		'ação rescisória',
		'boletim de ocorrência circunstanciada',
		'busca e apreensão em alienação fiduciária',
		'busca e apreensão infância e juventude',
		'busca e apreensão',
		'cancelamento e retif. de registro público (em geral)',
		'cancelamento e retif. de registro público',
		'carta arbitral',
		'carta de ordem criminal',
		'carta de ordem cível',
		'carta precatória criminal',
		'carta precatória cível',
		'carta precatória infracional',
		'carta precatória infância e juventude',
		'cautelar fiscal',
		'cautelar inominada criminal',
		'cautelar inominada infância e juventude',
		'cautelar inominada',
		'cobrança de cédula de crédito industrial',
		'conflito de competência',
		'compromisso arbitral',
		'concordata',
		'confirmação de testamento',
		'conflito de competência',
		'consignatória de aluguéis',
		'consignação em pagamento',
		'contraprotesto judicial',
		'conversão de separação judicial em divórcio',
		'correição extraordinária',
		'crime falimentar',
		'crimes ambientais',
		'crimes contra a propriedade imaterial',
		'crimes de calúnia, injúria e difamação de competência do juiz singular',
		'crimes de responsabilidade dos funcionários públicos',
		'cumprimento de sentença contra a fazenda pública',
		'cumprimento de sentença de obrigação de prestar alimentos',
		'cumprimento de sentença',
		'cumprimento de título executivo judicial',
		'cumprimento provisório de decisão',
		'curatela',
		'declaratória',
		'declaração de ausência',
		'demarcação / divisão',
		'depósito',
		'desapropriação',
		'despejo por falta de pagamento cumulado com cobrança',
		'despejo por falta de pagamento',
		'despejo',
		'dipo',
		'dissolução de sociedade de fato',
		'dissolução e liquidação de sociedade',
		'dissolução parcial de sociedade',
		'direta de inconstitucionalidade',
		'divórcio  litigioso',
		'divórcio consensual',
		'divórcio litigioso',
		'dppc',
		'dúvida',
		'embargos de declaração',
		'embargos de terceiro cível',
		'embargos de terceiro',
		'embargos à arrematação',
		'embargos à execução (inativa)',
		'embargos à execução fiscal',
		'embargos à execução',
		'execução contra a fazenda pública',
		'execução contra devedor solvente',
		'execução da pena',
		'execução de alimentos infância e juventude',
		'execução de alimentos',
		'execução de medida de segurança',
		'execução de medidas sócio',
		'execução de multa',
		'execução de sentença',
		'execução de título extajudicial contra a fazenda pública',
		'execução de título extrajudicial',
		'execução de título judicial',
		'execução extrajudicial de alimentos',
		'execução fiscal municipal',
		'execução fiscal',
		'execução hipotecária do sistema financeiro da habitação',
		'execução provisória',
		'execução',
		'exibição de documento ou coisa criminal',
		'exibição',
		'falência de empresários, sociedades empresáriais, microempresas e empresas de pequeno porte',
		'guarda c/c destituição do poder familiar',
		'guarda',
		'habeas corpus criminal',
		'habeas corpus',
		'habeas data',
		'habilitação de crédito',
		'habilitação para adoção',
		'habilitação',
		'herança jacente',
		'homologação da transação extrajudicial',
		'homologação de transação extrajudicial',
		'homologação em acordo de colaboração premiada',
		'imissão na posse',
		'impugnação ao cumprimento de decisão',
		'impugnação ao cumprimento de sentença',
		'impugnação de crédito',
		'impugnação de assistência judiciária',
		'incidente de desconsideração de personalidade jurídica',
		'incidente de falsidade',
		'indenização por dano moral',
		'inquérito policial',
		'insolvência civil',
		'insolvência requerida pelo credor',
		'insolvência requerida pelo devedor ou pelo espólio',
		'instrução de rescisória',
		'interdito proibitório',
		'interdição',
		'interpelação',
		'inventário',
		'liquidação de sentença pelo procedimento comum',
		'liquidação por arbitramento',
		'liquidação provisória de sentença pelo procedimento comum',
		'liquidação provisória por arbitramento',
		'mandado de segurança coletivo',
		'mandado de segurança cível',
		'mandado de segurança criminal',
		'mandado de segurança infância e juventude',
		'mandado de segurança',
		'medidas de proteção à criança e adolescente',
		'medidas protetivas de urgência (lei maria da penha) criminal',
		'medidas protetivas de urgência',
		'monitória',
		'nomeação de advogado',
		'notificação para explicações',
		'notificação',
		'nunciação de obra nova',
		'oposição',
		'outras medidas provisionais',
		'outros feitos não especificados',
		'outros incidentes não especificados (inativa)',
		'outros procedimentos de jurisdição voluntária',
		'pedido de busca e apreensão criminal',
		'pedido de falência',
		'pedido de medida de proteção',
		'pedido de prisão preventiva',
		'pedido de prisão temporária',
		'pedido de providências',
		'pedido de quebra de sigilo de dados e/ou telefônico',
		'perda ou suspensão do poder familiar',
		'petição criminal',
		'petição cível',
		'petição',
		'precatório',
		'prestação de contas',
		'procedimento  investigatório criminal',
		'procedimento comum cível',
		'procedimento comum infância e juventude',
		'procedimento comum',
		'procedimento conciliatório',
		'procedimento do juizado especial cível',
		'procedimento especial da lei antitóxicos',
		'procedimento especial dos crimes de abuso de autoridade',
		'procedimento especial',
		'procedimento investigatório criminal',
		'procedimento ordinário',
		'procedimento sumaríssimo',
		'procedimento sumário',
		'processo administrativo',
		'processo de apuração de ato infracional',
		'produção antecipada da prova',
		'produção antecipada de provas criminal',
		'protesto',
		'providência',
		'reclamação pré-processual',
		'recurso em sentido estrito',
		'reclamação',
		'reconvenção',
		'recuperação extrajudicial',
		'recuperação judicial',
		'recurso especial',
		'recurso inominado',
		'regulamentação de visitas',
		'reintegração / manutenção de posse',
		'reintegração de posse',
		'remessa necessária',
		'renovatória de locação',
		'representação criminal/notícia de crime',
		'requerimento de apreensão de veículo',
		'requerimento de reintegração de posse',
		'requisição de pequeno valor',
		'restauração de autos',
		'restituição de coisas apreendidas',
		'retificação de registro de imóvel',
		'retificação ou suprimento ou restauração de registro civil',
		'revisional de aluguel',
		'revisão criminal',
		'separação consensual',
		'separação de corpos',
		'separação litigiosa',
		'seqüestro',
		'sobrepartilha',
		'sonegados',
		'suprimento de idade e/ou consentimento',
		'termo circunstanciado',
		'tutela antecipada antecedente',
		'tutela c/c destituição do poder familiar',
		'tutela cautelar antecedente',
		'tutela cível',
		'tutela e curatela',
		'tutela infância e juventude',
		'tutela provisória',
		'tutela',
		'usucapião extraordinário',
		'usucapião'
		]

	return tipos_processuais
