def assuntos_proc():
	
	assuntos_proc = [
		'abandono intelectual',
		'abandono material',
		'abatimento proporcional do preço',
		'abono de permanência',
		'abuso de poder',
		'abuso sexual',
		'acessão',
		'acidente de trabalho',
		'acidente de trânsito',
		'acolhimento institucional',
		'acumulação de cargos',
		'acumulação de proventos',
		'adicional de fronteira',
		'adicional de horas extras',
		'adicional de insalubridade',
		'adicional de periculosidade',
		'adicional de produtividade',
		'adicional de serviço noturno',
		'adicional por tempo de serviço',
		'adimplemento e extinção',
		'adjudicação compulsória',
		'adjudicação',
		'administração de herança',
		'administração judicial',
		'administração',
		'admissão / permanência / despedida',
		'adoção de adolescente',
		'adoção de criança',
		'adoção de maior',
		'adoção nacional',
		'afastamento do cargo',
		'agenciamento',
		'agentes políticos',
		'agrotóxicos',
		'agêncie e distribuição',
		'alienação fiduciária',
		'alienação fiduciária',
		'alienação judicial',
		'alienação parental',
		'alimentação',
		'alimentos gravídicos',
		'alimentos',
		'alteração de coisa comum',
		'ameaça',
		'antecipação de tutela / tutela específica',
		'anulação de débito fiscal',
		'anulação e correção de provas / questões',
		'anulação',
		'apelação / remessa necessária',
		'apelação criminal',
		'apelação cível',
		'aposentadoria / pensão especial',
		'aposentadoria por invalidez acidentária',
		'aposentadoria por invalidez',
		'aposentadoria',
		'aposentadoria/retorno aotrabalho',
		'apreensão',
		'apropriação indébita',
		'apuração de haveres',
		'aquisição',
		'arras ou sinal',
		'arrendamento mercantil',
		'arrendamento mercantil',
		'arrendamento rural',
		'arrolamento de bens',
		'assembléia',
		'assinatura básica mensal',
		'assistência médico',
		'assistência social',
		'assistência à saúde',
		'associação para a produção e tráfico e condutas afins',
		'associação',
		'assunto não especificado',
		'assuntos antigos do saj',
		'assunção de dívida',
		'ato / negócio jurídico  f.t.s.',
		'ato / negócio jurídico',
		'ato infracional',
		'ato lesivo ao patrimônio artístico, estético, histórico ou turístico',
		'atos administrativos',
		'atos processuais',
		'atos unilaterais',
		'atraso de vôo',
		'autofalência',
		'auxílio',
		'avaliação para atestar dependência de drogas',
		'avaria',
		'averbação / contagem de tempo especial',
		'averbação / contagem recíproca',
		'averbação ou registro de sentença na matrícula do imóvel',
		'averbação/cômputo de tempo de serviço de segurado especial',
		'averbação/cômputo de tempo de serviço rural',
		'averbação/cômputo de tempo de serviço urbano',
		'averbação/cômputo/conversão de tempo de serviço especial',
		'bancários',
		'base de cálculo',
		'bem de família',
		'benefício assistencial',
		'benefícios em espécie',
		'benfeitorias',
		'bens públicos',
		'bloqueio de matrícula',
		'busca e apreensão de menores',
		'busca e apreensão',
		'cadastro de inadimplentes',
		'calúnia',
		'cancelamento de protesto',
		'cancelamento de vôo',
		'capacidade',
		'capitalização / anatocismo',
		'capitalização e previdência privada',
		'cargo em comissão',
		'carta testemunhável',
		'cartão de crédito',
		'casamento',
		'causas supervenientes à sentença',
		'caução / contracautela',
		'caução',
		'cessão de crédito',
		'cessão de créditos',
		'cheque',
		'citação',
		'classificação de créditos',
		'classificação e/ou preterição',
		'classificação indicativa',
		'cláusula penal',
		'cláusulas abusivas',
		'cnh',
		'cobrança de aluguéis',
		'cobrança',
		'cofins',
		'coisas',
		'combustíveis e derivados',
		'comercialização e/ou utilização sem restrições de medicamentos',
		'comissão',
		'comodato',
		'compensação',
		'competência tributária',
		'complementação de benefício/ferroviário',
		'compra e venda',
		'compromisso',
		'comunicação social',
		'concessão / permissão / autorização',
		'concessão de auxílio doença',
		'concessão',
		'concurso de credores',
		'concurso público / edital',
		'condições especiais para prestação de prova',
		'condomínio em edifício',
		'condomínio',
		'conflito de competência cível',
		'confusão',
		'conselhos regionais e afins',
		'conselhos tutelares',
		'consensual de adolescente',
		'constituição de renda',
		'constituição',
		'constrição / penhora / avaliação / indisponibilidade de bens',
		'constrição / penhora / avaliação / indisponibilidade debens',
		'constrição / penhora / avaliação / indisponibilidadede bens',
		'constrição / penhora / avaliação/ indisponibilidade de bens',
		'constrição / penhora /avaliação / indisponibilidade de bens',
		'constrição / penhora/ avaliação / indisponibilidade de bens',
		'constrição /penhora / avaliação / indisponibilidade de bens',
		'constrição/penhora / avaliação / indisponibilidade de bens',
		'constrição/penhora/avaliação/indisponibilidade de bens',
		'consórcio',
		'conta de participação',
		'contratos administrativos',
		'contratos bancários',
		'contratos de consumo',
		'contravenções penais',
		'contribuição sobre a folha de salários',
		'contribuição social sobre o lucro líquido',
		'contribuições corporativas',
		'contribuições de melhoria',
		'contribuições especiais',
		'contribuições previdenciárias',
		'contribuições',
		'conversão',
		'convolação de recuperação judicial em falência',
		'convênio',
		'correição parcial cível',
		'corretagem',
		'correção monetária',
		'corrupção passiva',
		'criação',
		'crime de descumprimento de medidas protetivas de urgência',
		'crimes contra a dignidade sexual',
		'crimes contra a fauna',
		'crimes contra a flora',
		'crimes contra a honra',
		'crimes contra a ordem econômica',
		'crimes contra a ordem tributária',
		'crimes contra a propriedade intelectual de programa de computador',
		'crimes contra a propriedade intelectual',
		'crimes contra a vida',
		'crimes contra o meio ambiente e o patrimônio genético',
		'crimes contra o mercado de capitais',
		'crimes de responsabilidade',
		'crimes de tortura',
		'crimes de tráfico ilícito e uso indevido de drogas',
		'crimes de trânsito',
		'crimes do sistema nacional de armas',
		'crimes falimentares',
		'crimes previstos no estatuto da criança e do adolescente',
		'crimes previstos no estatuto do idoso',
		'crédito rural',
		'crédito tributário',
		'créditos / privilégios marítimos',
		'cumprimento provisório de sentença',
		'cumulação',
		'curadoria dos bens do ausente',
		'curso de formação',
		'custas',
		'custeio de assistência médica',
		'cálculo do fator previdenciário',
		'câmbio',
		'cédula de crédito bancário',
		'cédula de crédito comercial',
		'cédula de crédito industrial',
		'cédula de crédito rural',
		'cédula de crédito à exportação',
		'cédula de produto rural',
		'cédula hipotecária',
		'dano ambiental',
		'dano ao erário',
		'dano qualificado',
		'dano',
		'data base',
		'dação em pagamento',
		'debêntures',
		'decadência',
		'decorrente de violência doméstica',
		'defeito, nulidade ou anulação',
		'deficiente',
		'demissão ou exoneração',
		'denunciação caluniosa',
		'depósito',
		'desabamento ou desmoronamento',
		'desacato',
		'desaforamento de julgamento',
		'desapropriação de imóvel urbano',
		'desapropriação indireta',
		'desapropriação',
		'desconsideração da personalidade jurídica',
		'desconto em folha de pagamento',
		'descontos indevidos',
		'descumprimento deveres poder familiar',
		'desenho industrial',
		'despejo para uso de ascendentes e descendentes',
		'despejo para uso próprio',
		'despejo por denúncia vazia',
		'despesas condominiais',
		'destituição de poder familiar',
		'dever de informação',
		'devolução de contribuições previdenciárias pagas além do teto',
		'difamação',
		'direito administrativo e outras matérias de direito público',
		'direito autoral',
		'direito civil',
		'direito da criança e do adolescente',
		'direito de imagem',
		'direito de preferência',
		'direito de vizinhança',
		'direito do consumidor',
		'direito previdenciário',
		'direito processual civil e do trabalho',
		'direito tributário',
		'direitos / deveres do condômino',
		'direitos da personalidade',
		'direitos e títulos de crédito',
		'direitos e títulos de crédito',
		'direito de adolescente',
		'dispensa',
		'disponibilidade / aproveitamento',
		'dissolução',
		'divisão e demarcação',
		'diárias e outras indenizações',
		'doação',
		'duplicata',
		'dívida ativa não',
		'dívida ativa',
		'edital',
		'educativas',
		'efeito suspensivo / impugnação / embargos à execução',
		'eleição',
		'embargos de declaração criminal',
		'embargos de declaração cível',
		'empregado público / temporário',
		'empreitada',
		'empresas',
		'empréstimo consignado',
		'encaminhamento aos pais ou responsável, mediante termo de responsabilidade',
		'energia elétrica',
		'enquadramento',
		'enriquecimento ilícito',
		'enriquecimento sem causa',
		'ensino fundamental e médio',
		'ensino superior',
		'entidade de apoio socioeducativo em meio aberto',
		'entidades de atendimento',
		'entrada e permanência de menores',
		'equivalência salarial',
		'erro médico',
		'esbulho / turbação / ameaça',
		'escolaridade',
		'espécies de contratos',
		'espécies de títulos de crédito',
		'estabelecimentos de ensino',
		'estabilidade',
		'estatuto da criança e do adolescente',
		'estatuto do idoso',
		'estelionato',
		'estimatório',
		'estupro de vulnerável',
		'estupro',
		'evicção ou vicio redibitório',
		'exame de saúde e/ou aptidão física',
		'exame psicotécnico / psiquiátrico',
		'exclusão de associado',
		'exclusão de herdeiro ou legatário',
		'exclusão',
		'execução contratual',
		'execução previdenciária',
		'exercício arbitrário das próprias razões',
		'exoneração',
		'expedição de alvará judicial',
		'expedição de alvará judicial',
		'expropriação de bens',
		'expurgos inflacionários / planos econômicos',
		'extinção da execução',
		'extinção das obrigações do falido',
		'extinção do crédito tributário',
		'extinção',
		'extorsão',
		'extravio de bagagem',
		'falsidade ideológica',
		'falta de assistência',
		'família',
		'fato atípico',
		'fato gerador/incidência',
		'fatos jurídicos',
		'fauna',
		'fazenda nacional',
		'federais',
		'feminicídio',
		'fgts/fundo de garantia por tempo de serviço',
		'fiança',
		'financiamento de produto',
		'financiamento do sus',
		'fiscalização',
		'fixação',
		'flora',
		'fornecimento de energia elétrica',
		'fornecimento de medicamentos',
		'fornecimento de medicamentos',
		'fornecimento de água',
		'franquia',
		'fraude à execução',
		'funcionamento de estabelecimentos empresariais',
		'furto qualificado',
		'furto',
		'férias',
		'garantias constitucionais',
		'gestante / adotante / paternidade',
		'gestão de negócios',
		'gratificação de incentivo',
		'gratificação incorporada / quintos e décimos / vpni',
		'gratificações de atividade',
		'gratificações e adicionais',
		'gratificações estaduais específicas',
		'gratificações municipais específicas',
		'guarda com genitor ou responsável no exterior',
		'guarda',
		'habilitação / registro cadastral / julgamento / homologação',
		'habilitação de crédito (inativa)',
		'habilitação para casamento',
		'habitação',
		'hipoteca',
		'homicídio privilegiado',
		'homicídio qualificado',
		'homicídio simples',
		'honorários advocatícios em execução contra a fazenda pública',
		'honorários advocatícios',
		'honorários periciais',
		'hora extra',
		'hospitais e outras unidades de saúde',
		'icms / incidência sobre o ativo fixo',
		'icms/ imposto sobre circulação de mercadorias',
		'icms/ imposto sobre circulação de mercadorias',
		'icms/importação',
		'idoso',
		'imissão na posse',
		'imissão',
		'impostos',
		'improbidade administrativa',
		'imputação do pagamento',
		'imunidade de execução',
		'imunidade',
		'inadimplemento',
		'incapacidade laborativa parcial',
		'incapacidade laborativa permanente',
		'incapacidade laborativa temporária',
		'inclusão de dependente',
		'inclusão em programa comunitário ou oficial de auxílio à família, à criança e ao adolescente',
		'inclusão em programa oficial ou comunitário de auxílio',
		'inclusão indevida em cadastro de inadimplentes'
		'inclusão indevida em cadastro de inadimplentes',
		'inclusão indevida em cadastro de inadimplentes',
		'incorporação imobiliária',
		'incêndio culposo',
		'indenizaçao por dano moral',
		'indenização do prejuízo',
		'indenização por dano ambiental',
		'indenização por dano material',
		'indenização por dano moral',
		'indenização por erro judiciário',
		'indenização trabalhista',
		'indenizações regulares',
		'industrial / mercantil',
		'ineficácia de atos em relação à massa',
		'infração administrativa',
		'infrações administrativas',
		'ingresso e concurso',
		'ingresso e exclusão dos sócios na sociedade',
		'injúria',
		'inocorrência de vício insanável',
		'inquérito / processo / recurso administrativo',
		'inscrição / documentação',
		'inspeção fitossanitária',
		'interdição',
		'interesse particular',
		'internação',
		'interpretação / revisão de contrato',
		'intervenção de terceiros',
		'intervenção do estado na propriedade',
		'intervenção em estado / município',
		'intimação / notificação',
		'intimação',
		'invalidez permanente',
		'inventário e partilha',
		'inventário e partilha',
		'inventário e partilha',
		'investigação de maternidade',
		'investigação de paternidade',
		'ipi/ imposto sobre produtos industrializados',
		'iptu/ imposto predial e territorial urbano',
		'ipva',
		'irpf/imposto de renda de pessoa física',
		'irpj/imposto de renda de pessoa jurídica',
		'irredutibilidade de vencimentos',
		'irregularidade no atendimento',
		'isenção',
		'isonomia/equivalência salarial',
		'iss/ imposto sobre serviços',
		'itbi',
		'itcd',
		'itr/ imposto territorial rural',
		'jogos / sorteios / promoções comerciais',
		'jornada de trabalho',
		'juros de mora',
		'juros',
		'juros/correção monetária',
		'lançamento',
		'lei de imprensa',
		'lesão corporal',
		'letra de câmbio',
		'levantamento de valor',
		'levantamento de valor',
		'levantamento',
		'liberação de veículo apreendido',
		'liberdade provisória com ou sem fiança',
		'licenciamento de veículo',
		'licença por acidente em serviço',
		'licença prêmio',
		'licença',
		'licenças / afastamentos',
		'licenças',
		'licitações',
		'liminar',
		'limitada',
		'limitação de fim de semana',
		'limitação de juros',
		'liquidação / cumprimento / execução',
		'liquidação',
		'livramento condicional',
		'locação / permissão / concessão / autorização / cessão de uso',
		'locação de imóvel',
		'locação de móvel',
		'mandato',
		'manutenção de posse',
		'manutenção do benefício pela equivalência salarial',
		'marca',
		'matrícula e frequência obrigatória em estabelecimento oficial de ensino fundamental',
		'maus tratos',
		'medida cautelar',
		'medidas de proteção',
		'meio ambiente',
		'militar',
		'modalidade / limite / dispensa / inexigibilidade',
		'moradia',
		'movimentos repetitivos/tenossinovite/ler/dort',
		'multa cominatória / astreintes',
		'multa',
		'multas e demais sanções',
		'municipais',
		'mútuo',
		'naturalização',
		'nomeação de administrador provisório',
		'nomeação',
		'nota de crédito comercial',
		'nota de crédito rural',
		'nota fiscal ou fatura',
		'nota promissória',
		'novação',
		'nulidade / anulação',
		'nulidade / inexigibilidade do título',
		'nulidade e anulação de partilha e adjudicação de herança',
		'nulidade e anulação de testamento',
		'nulidade',
		'não discriminação',
		'objetos de cartas precatórias/de ordem',
		'obrigação de entregar',
		'obrigação de fazer / não fazer',
		'obrigação de fazer /não fazer',
		'obrigação de fazer/não fazer',
		'obrigações',
		'oferecidas',
		'oferecimento de drogas para consumo conjunto',
		'oferta e publicidade',
		'oferta',
		'ordem urbanística',
		'ordenação da cidade / plano diretor',
		'ordenação da cidade /plano diretor',
		'organização político',
		'overbooking',
		'pagamento atrasado / correção monetária',
		'pagamento com sub',
		'pagamento em consignação',
		'pagamento indevido',
		'pagamento',
		'parcelamento do solo',
		'parcelamento',
		'parcelas de benefício não pagas',
		'parceria agrícola e/ou pecuária',
		'participação em certames de beleza',
		'participação em espetáculos públicos e seus ensaios',
		'patente',
		'peculato',
		'pedido de falência',
		'pedido de prisão temporária',
		'pedido de uniformização de interpretação de lei cível',
		'pena privativa de liberdade',
		'pena restritiva de direitos',
		'penalidades',
		'penhor',
		'pensão',
		'perda da propriedade',
		'perda ou modificação de guarda',
		'perdas e danos',
		'perturbação do trabalho ou do sossego alheios',
		'pessoa idosa',
		'pessoas com deficiência',
		'pessoas naturais',
		'petição de herança',
		'pis',
		'piso salarial',
		'plano de classificação de cargos',
		'planos de saúde',
		'plantão',
		'poluição',
		'posse de drogas para consumo pessoal',
		'posse e exercício',
		'posse',
		'posturas municipais',
		'precatório',
		'preferências e privilégios creditórios',
		'prescrição e decadência',
		'prescrição',
		'prestação de contas',
		'prestação de serviços à comunidade',
		'prestação de serviços',
		'prestação pecuniária',
		'previdência privada',
		'prisão civil',
		'prisão em flagrante',
		'processo disciplinar / sindicância',
		'processo e procedimento',
		'produto impróprio',
		'programa de computador',
		'promessa de compra e venda',
		'promessa de recompensa',
		'promoção / ascensão',
		'promoção',
		'propriedade fiduciária',
		'propriedade intelectual / industrial',
		'propriedade resolúvel',
		'propriedade',
		'protesto indevido de título',
		'provas em geral',
		'provas',
		'provisionais',
		'práticas abusivas',
		'pulsos excedentes',
		'quitação',
		'readaptação',
		'reajuste contratual',
		'reajuste de prestações',
		'reajuste de remuneração, soldo, proventos ou pensão',
		'reajustes de remuneração, proventos ou pensão',
		'reajustes e revisões específicos',
		'recebimento de bolsa de estudos',
		'receptação culposa',
		'receptação qualificada',
		'receptação',
		'reclamação do extrajudicial',
		'recolhimento e tratamento de lixo',
		'recondução',
		'reconhecimento / dissolução',
		'recuperação extrajudicial',
		'recuperação judicial e falência',
		'recurso em sentido estrito',
		'recurso em sentido estrito/recurso ex officio',
		'recurso inominado cível',
		'recursos administrativos',
		'recursos hídricos',
		'redução da capacidade auditiva',
		'regime de bens entre os cônjuges',
		'regime estatutário',
		'regime inicial',
		'regime previdenciário',
		'regime',
		'registro civil das pessoas naturais',
		'registro civil de pessoas jurídicas',
		'registro de empresa',
		'registro de imóveis',
		'registro de nascimento após prazo legal',
		'registro de óbito após prazo legal',
		'registros públicos',
		'regulamentação de visitas',
		'regularização de guarda',
		'reintegração',
		'reivindicação',
		'relatório de investigações',
		'relações de parentesco',
		'remessa necessária criminal',
		'remessa necessária cível',
		'remissão das dívidas',
		'remição do imóvel hipotecado',
		'remição',
		'remoção e dispensa',
		'remoção',
		'remuneração',
		'renda mensal vitalícia',
		'renúncia ao benefício',
		'repetição de indébito',
		'representação comercial',
		'requerimento de reintegração de posse',
		'requisição de pequeno valor',
		'requisição de tratamento médico, psicológico ou psiquiátrico, em regime hospitalar ou ambulatorial',
		'requisição para tratamento de sua saúde, em regime ambulatorial, hospitalar ou domiciliar',
		'rescisão / resolução',
		'rescisão do contrato e devolução do dinheiro',
		'rescisão do contrato e devolução do dinheiro',
		'rescisão do contrato e devolução do dinheiro',
		'rescisão',
		'reserva de vagas para deficientes',
		'reserva remunerada',
		'resgate de contribuição',
		'resistência',
		'responsabilidade civil do empregador',
		'responsabilidade civil do servidor público / indenização ao erário',
		'responsabilidade civil',
		'responsabilidade contratual',
		'responsabilidade da administração',
		'responsabilidade do fornecedor',
		'responsabilidade dos sócios e administradores',
		'responsabilidade extracontratual',
		'responsabilidade tributária',
		'restabelecimento da sociedade conjugal',
		'restabelecimento',
		'restauração',
		'restituição de coisa ou dinheiro na falência do devedor empresário',
		'retificação de assento de óbito',
		'retificação de data de nascimento',
		'retificação de nome',
		'retificação de sexo',
		'retificação de área de imóvel',
		'reversão',
		'revisão de tutela antecipada antecedente',
		'revisão do saldo devedor',
		'revisão geral anual',
		'revisão judicial de decisão do conselho tutelar',
		'revisão',
		'revogação de atos praticados em prejuízo de credores e da massa',
		'revogação',
		'revogação/anulação de multa ambiental',
		'revogação/concessão de licença ambiental',
		'roubo majorado',
		'roubo',
		'rural',
		'salário maternidade',
		'salário',
		'saneamento',
		'sanções administrativas',
		'saúde mental',
		'saúde',
		'segurança em edificações',
		'seguro acidentes do trabalho',
		'seguro',
		'separação de corpos',
		'seqüestro e cárcere privado',
		'servidor público civil',
		'servidores ativos',
		'servidores inativos',
		'servidão administrativa',
		'servidão',
		'serviço militar',
		'serviços hospitalares',
		'serviços profissionais',
		'serviços',
		'seção cível',
		'simples',
		'sistema de proteção especial a vítimas e a testemunhas',
		'sistema financeiro da habitação',
		'sistema nacional de trânsito',
		'sistema remuneratório e benefícios',
		'sociedade de ensino superior toledo ltda',
		'sociedade',
		'substituição da parte',
		'substituição do produto',
		'subsídios',
		'sucessão provisória',
		'sucessão',
		'sucessões',
		'sucumbência',
		'suprimento de capacidade ou de consentimento para casar',
		'suspensão condicional da pena',
		'suspensão da exigibilidade',
		'suspensão',
		'sustação de protesto',
		'sustação/alteração de leilão',
		'tabela price',
		'tabelionatos, registros, cartórios',
		'tarifas',
		'taxa de coleta de lixo',
		'taxa de fiscalização ambiental',
		'taxa de licenciamento de estabelecimento',
		'taxa de limpeza pública',
		'taxa de ocupação / laudêmio / foro',
		'taxa de prevenção e combate a incêndio',
		'taxa judiciária',
		'taxas',
		'telefonia',
		'tempo de serviço',
		'tempo de serviço',
		'terceirização do sus',
		'teto salarial',
		'tomada de decisão apoiada',
		'transação',
		'transferência de cotas',
		'transferência de financiamento',
		'transferência para o regime fechado',
		'transferência para o regime semiaberto',
		'transferência',
		'transporte aquaviário',
		'transporte aéreo',
		'transporte de coisas',
		'transporte de pessoas',
		'transporte ferroviário',
		'transporte rodoviário',
		'transporte terrestre',
		'tratamento ambulatorial',
		'tratamento da própria saúde',
		'tratamento médico',
		'troca ou permuta',
		'tráfico de drogas e condutas afins',
		'turismo',
		'tutela de evidência',
		'tutela de urgência',
		'tutela e curatela',
		'títulos da dívida pública',
		'títulos de crédito',
		'ultraje público ao pudor',
		'unidade de conservação da natureza',
		'unidade de terapia intensiva',
		'unilateral de adolescente',
		'unilateral de criança',
		'união estável ou concubinato',
		'união homoafetiva',
		'união',
		'uso de documento falso',
		'uso ou tráfico de drogas',
		'uso',
		'usucapião conjugal',
		'usucapião especial coletiva',
		'usucapião especial',
		'usucapião extraordinária',
		'usucapião ordinária',
		'usufruto e administração dos bens de filhos menores',
		'usufruto',
		'utilização de bens públicos',
		'vaga de garagem',
		'vaga em creche',
		'vaga em ensino pré',
		'valor da execução / cálculo / atualização',
		'vendas casadas',
		'veículos',
		'viagem ao exterior',
		'viagem nacional',
		'vigilância sanitária e epidemiológica',
		'violação aos princípios administrativos',
		'violação de direito autoral',
		'violação de domicílio',
		'violência doméstica contra a mulher',
		'vistoria',
		'voluntária',
		'vícios de construção',
		'warrant',
		'água e/ou esgoto',
		'área de preservação permanente'
		]
	return assuntos_proc
